# Generated by Django 5.1.3 on 2024-12-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_record_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='region',
            field=models.CharField(choices=[('Balkans', 'Balkans'), ('Central Europe', 'Central Europe'), ('Eastern Europe', 'Eastern Europe'), ('Northern Europe', 'Northern Europe'), ('Southern Europe', 'Southern Europe'), ('Turkey', 'Turkey'), ('China', 'China'), ('East Asia', 'East Asia'), ('South Asia', 'South Asia'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
