# Generated by Django 5.1.3 on 2024-11-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('companies', models.ManyToManyField(to='companies.company')),
                ('products', models.ManyToManyField(to='products.product')),
            ],
        ),
    ]
