# Generated by Django 5.1.3 on 2024-11-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('business_field', models.CharField(choices=[('Construction', 'Construction'), ('Engineering', 'Engineering'), ('Machine building', 'Machine building'), ('Shipbuilding', 'Shipbuilding'), ('Steel production', 'Steel production'), ('Unknown', 'Unknown')], default='Unknown', max_length=50)),
                ('products', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
