# Generated by Django 5.1.3 on 2024-12-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='business_field',
            field=models.CharField(choices=[('Construction', 'Construction'), ('Engineering', 'Engineering'), ('Machine building', 'Machine building'), ('Shipbuilding', 'Shipbuilding'), ('Steel production', 'Steel production'), ('Steel trade', 'Steel trade'), ('Unknown', 'Unknown')], default='Unknown', max_length=50),
        ),
    ]
